#!/usr/bin/env bash
# generate-review-instructions.sh
#
# Generates .github/instructions/code-review.instructions.md from:
#   1. review-rules in docs/decisions/ ADR front matter
#   2. Static rules in .github/instructions/review-rules-static.md
#
# Usage:
#   Scripts/generate-review-instructions.sh          # Generate / overwrite
#   Scripts/generate-review-instructions.sh --check  # Exit non-zero if stale

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DECISIONS_DIR="$REPO_ROOT/docs/decisions"
STATIC_RULES="$REPO_ROOT/.github/instructions/review-rules-static.md"
OUTPUT="$REPO_ROOT/.github/instructions/code-review.instructions.md"

check_mode=false
if [[ "${1:-}" == "--check" ]]; then
    check_mode=true
fi

# --- Build output in memory ---

output="---
applyTo: \"**\"
---
<!-- Auto-generated by Scripts/generate-review-instructions.sh — do not edit manually -->
<!-- Re-generate with: Scripts/generate-review-instructions.sh -->

# Code Review Instructions — Snap
"

# --- Extract review-rules from ADRs ---

adr_rules=""
for adr in "$DECISIONS_DIR"/[0-9]*.md; do
    [[ -f "$adr" ]] || continue

    # Read front matter (between first and second ---)
    in_frontmatter=false
    frontmatter=""
    title=""
    while IFS= read -r line; do
        if [[ "$line" == "---" ]]; then
            if $in_frontmatter; then
                break
            else
                in_frontmatter=true
                continue
            fi
        fi
        if $in_frontmatter; then
            frontmatter+="$line"$'\n'
        fi
    done < "$adr"

    # Check status is decided
    status=$(echo "$frontmatter" | grep -E '^status:' | head -1 | sed 's/^status:[[:space:]]*//' | sed 's/[[:space:]]*#.*//')
    [[ "$status" == "decided" ]] || continue

    # Extract title (first # heading after front matter)
    title=$(grep -m1 '^# ' "$adr" | sed 's/^# //')

    # Extract ADR number from filename
    adr_num=$(basename "$adr" | grep -oE '^[0-9]+')

    # Extract review-rules from front matter only (not from body prose)
    in_rules=false
    while IFS= read -r line; do
        if [[ "$line" =~ ^review-rules: ]]; then
            in_rules=true
            continue
        fi
        if $in_rules; then
            if [[ "$line" =~ ^[[:space:]]+-[[:space:]] ]]; then
                rule=$(echo "$line" | sed 's/^[[:space:]]*-[[:space:]]*//' | sed 's/^"//' | sed 's/"$//')
                adr_rules+="- **ADR-${adr_num}** (${title}): ${rule}"$'\n'
            else
                break
            fi
        fi
    done <<< "$frontmatter"
done

if [[ -n "$adr_rules" ]]; then
    output+="
## Architecture Decision Rules

These rules reflect decisions documented in \`docs/decisions/\`. Do not flag
these as issues — they are intentional.

${adr_rules}"
fi

# --- Append static rules ---

if [[ -f "$STATIC_RULES" ]]; then
    output+="
$(cat "$STATIC_RULES")
"
fi

# --- Write or check ---

if $check_mode; then
    if [[ ! -f "$OUTPUT" ]]; then
        echo "ERROR: $OUTPUT does not exist. Run without --check to generate." >&2
        exit 1
    fi
    if ! diff -q <(echo "$output") "$OUTPUT" > /dev/null 2>&1; then
        echo "ERROR: $OUTPUT is stale. Run Scripts/generate-review-instructions.sh to update." >&2
        diff <(echo "$output") "$OUTPUT" >&2 || true
        exit 1
    fi
    echo "OK: $OUTPUT is up to date."
    exit 0
fi

mkdir -p "$(dirname "$OUTPUT")"
echo "$output" > "$OUTPUT"
echo "Generated $OUTPUT"
